<a href="https://colab.research.google.com/github/devanggarg1/Mini-Project/blob/main/Image_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install ipython-autotime
%load_ext autotime

time: 143 µs (started: 2021-05-06 03:11:32 +00:00)


In [2]:
!pip install bing-image-downloader

In [3]:
!mkdir images

In [4]:
from bing_image_downloader import downloader
downloader.download("pretty sunflower",limit=30,output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://66.media.tumblr.com/44d35612a2a7601c2f8c8d35cf820193/tumblr_nqalbc4ywM1rwrn5zo1_500.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/736x/21/c8/e2/21c8e2c6a8ccbdd74c5cf5ffd1b388c6.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://services.autoclubmo.aaa.com/traveler/images/2014/07/Janice_Poole_Sunflower.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://www.prettydesigns.com/wp-content/uploads/2014/06/Green-Nails2.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/736x/0e/b5/63/0eb5635680546f8bb7bc618ad0e55489.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/736x/49/7b/d5/497bd55f180f61f0eb1d49162b808fbd.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/736x/09/80/ac/0980ac563d88b546bdf9ce93e0c54ccf--preschool-printables-preschool-crafts.jpg
[%] File Do

In [5]:
downloader.download("rugby ball leather",limit=30,output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://cdn.notonthehighstreet.com/system/product_images/images/000/393/351/original_CF016852.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://cdn.shopify.com/s/files/1/0788/5979/products/mvp-leather-balls-heritage-leather-rugby-ball-1_1024x1024.jpg?v=1550134680
[%] File Downloaded !

[%] Downloading Image #3 from https://images.antiquesatlas.com/dealer-stock-images/puckeringsantiques/Antique_Novelty_Travel_Inkwell_as584a1568z-3.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.john-woodbridge.com/1536-tm_large_default/leather-vintage-football-allen-1938.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://cdn.thinglink.me/api/image/586569159714799617/1240/10/scaletowidth
[%] File Downloaded !

[%] Downloading Image #6 from https://www.upfrontcricket.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/j/n/jnrclub_cb_edited-2.jpg
[%]

In [6]:
downloader.download("ice cream cone",limit=30,output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 11 Images on Page 1.


[%] Downloading Image #1 from https://cdn001.cakecentral.com/gallery/2017/07/900_melting-ice-cream-cone-997041mFIfl.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.barnorama.com/wp-content/uploads/2018/12/Funny-Pictures-1904-72.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://littlebitsof.com/wp-content/uploads/2014/04/DSC_0131.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://media.istockphoto.com/photos/melting-ice-cream-cone-picture-id1007165770?k=6&amp;m=1007165770&amp;s=170667a&amp;w=0&amp;h=VlX1UdiHoBsDpdYszyHEpusCA9Ia0GbsPwBNq3BN1Jg=
[%] File Downloaded !

[%] Downloading Image #5 from http://akns-images.eonline.com/eol_images/Entire_Site/2014910/rs_300x300-141010052310-600.Joe-Biden-JR-101014.jpg?downsize=600:315
[%] File Downloaded !

[%] Downloading Image #6 from https://family.disney.com/wp-content/uploads/2018/07/icecream-wallpaper-2.jpg
[Error]Invalid image, not s

In [12]:
#preprocess data

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target=[]
images=[]
flat_data=[]

DATADIR='/content/images'
CATEGORIES=['pretty sunflower','rugby ball leather','ice cream cone']

for category in CATEGORIES:
  class_num=CATEGORIES.index(category)
  path=os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img))
    img_resized=resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

flat_data=np.array(flat_data)
target=np.array(target)
images=np.array(images)

time: 19.7 s (started: 2021-05-06 03:46:14 +00:00)


In [14]:
#split data into training and testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(flat_data,target,test_size=0.3,random_state=109)

time: 16.7 ms (started: 2021-05-06 03:53:35 +00:00)


In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid=[
            {'C':[1,10,100,1000],'kernel':['linear']},
            {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]

svc=svm.SVC(probability=True)
clf=GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 1min 32s (started: 2021-05-06 04:16:29 +00:00)


In [19]:
y_pred=clf.predict(x_test)
y_pred

array([1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1])

time: 128 ms (started: 2021-05-06 04:20:25 +00:00)


In [20]:
y_test

array([1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1])

time: 5.36 ms (started: 2021-05-06 04:20:36 +00:00)


In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix

time: 921 µs (started: 2021-05-06 04:19:28 +00:00)


In [21]:
accuracy_score(y_pred,y_test)

0.9629629629629629

time: 6.91 ms (started: 2021-05-06 04:21:09 +00:00)


In [22]:
confusion_matrix(y_pred,y_test)

array([[ 8,  0,  0],
       [ 0, 11,  1],
       [ 0,  0,  7]])

time: 5.98 ms (started: 2021-05-06 04:21:37 +00:00)


In [23]:
#save the model using pickle library

import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 30.2 ms (started: 2021-05-06 04:23:32 +00:00)


In [24]:
model=pickle.load(open('img_model.p','rb'))

time: 16.7 ms (started: 2021-05-06 04:24:58 +00:00)


In [ ]:
#testing a brand new image

flat_data=[]
url=input('Enter your URL')
img=imread(url)
image_resized=resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out=model.predict(flat_data)
y_out=CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT : {y_out}')